/*
* Copyright (C) The Community OpenORB Project. All rights reserved.
*
* This software is published under the terms of The OpenORB Community Software
* License version 1.0, a copy of which has been included with this distribution
* in the LICENSE.txt file.
*/

module obv
{
    module support_abstract
    {
        abstract interface AnAbstractInterface
        {
            void print();
        };

        interface Example : AnAbstractInterface
        {
        };

        valuetype valueExample supports AnAbstractInterface
        {
            public string name_state;
        };

        interface ValueExchange
        {
            AnAbstractInterface getInterface( in boolean byValue );
        };
    };
};
